server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heimademo?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.leyou.userservice.pojo
